services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOCAL=true
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./app:/code/app
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
      POSTGRES_PORT: "${DB_PORT:-5432}"
      APP_ENV: "${APP_ENV:-development}"
      SECRET_KEY: "${SECRET_KEY:-changeme}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
